name: business_umbrella
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  retrofit: 3.0.1
  cupertino_icons: ^1.0.6
  lottie: ^2.6.0
  animated_splash_screen: ^1.3.0
  qr_flutter: ^4.1.0
  flutter_barcode_scanner: ^2.0.0
  barcode_widget: ^2.0.4
  qr_code_scanner: ^1.0.1
  flutter_launcher_icons: ^0.9.3
  intl_phone_number_input: ^0.7.3+1
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: 2.1.11
  retrofit_generator: 4.0.3+2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_native_splash:
  color: "#fafafa"
  image: "lib/assets/IEC.png"
  ios_content_mode: scaleAspectFill
  android_gravity: fill


flutter_launcher_icons:
  image_path: "lib/assets/iec_logo.png"
  android: true
  ios: true

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - lib/assets/IEC_Presentation.json
   - lib/assets/pay_now_qr_code.png
   - lib/assets/IEC.png
   - lib/assets/iec_logo.png
   - lib/assets/goal.png
   - lib/assets/logout.png
   - lib/assets/messages.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
